board/urls.py
from django.urls import path
from . import views

app_name='board'
urlpatterns = [
    path('', views.index, name='home'),
    path('board', views.board_list)

]

hee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
]

board/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class notice_list(models.Model):
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=4000)
    writer = models.CharField(max_length=10)
    write_dttm = models.DateTimeField(default=datetime.now())
    good_cnt = models.IntegerField(default=0)

board/views.py
from board.models import notice_list
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request,'board/index.html')

def board_list(request):
    notice = notice_list.objects.all().order_by('-id')
    context = {'notice':notice}
    return render(request, 'board/board_list.html', context)

board/templates/board/board_list.html
{% extends "board/layout.html" %}
{% block title %}

{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>글번호</B></td>
            <td><B>제목</B></td>
            <td><B>작성자</B></td>
            <td><B>작성일자</B></td>
            <td><B>좋아요</B></td>
        </tr>
        </thead>
        <tbody>
        {% for notice in notice %}
        <tr>
            <td>{{notice.id}}</td>
            <td>{{notice.title}}</td>
            <td>{{notice.writer}}</td>
            <td>{{notice.write_dttm}}</td>
            <td>{{notice.good_cnt}}</td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
{% endblock %}

board/templates/board/index.html
{% extends "board/layout.html" %}
{% block title %}

{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>출마지역</B></td>
            <td><B>기호</B></td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>번</td>
        </tr>
        <tbody>
    </table>
{% endblock %}

board/templates/board/layout.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/darkly/bootstrap.min.css" integrity="sha384-nNK9n28pDUDDgIiIqZ/MiyO3F4/9vsMtReZK39klb/MtkZI3/LtjSjlmyVPS3KdN" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>

        <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'board:home' %}"> 장고를 활용한 웹서버 띄우기</a>
              </div>
          </nav>
        {% block content %}{% endblock %}
    </body>
</html>